version: '3.7'

services:
    web:
        build: .
        restart: always
        ports:
            - "4001:4001"
        environment:
            - SECRET_KEY
            - DATABASE_URI=sqlite:////db/data
        volumes:
            - db:/db
            - uploads:/src/static/pr

volumes:
  db:
  uploads:
